trigger:
  batch: true
  branches:
    include:
    - trunk

pr:
  branches:
    include:
    - trunk

variables:
  INFRASTRUCTURE: "AZUREPIPELINES"
  TRIAL_REPORTER: "verbose"

jobs:

- template: 'macos_test_jobs.yml'
  parameters:
    pythonVersions:
      py27: "2.7"
      py36: "3.6"
      py37: "3.7"

- template: 'windows_test_jobs.yml'
  parameters:
    pythonVersions:
      py27: "2.7"
      py36: "3.6"
      py37: "3.7"
    reactor: select

- template: 'windows_test_jobs.yml'
  parameters:
    pythonVersions:
      py27: "2.7"
      py36: "3.6"
      py37: "3.7"
    reactor: iocp
