trigger:
  batch: true
  branches:
    include:
    - trunk

pr:
  branches:
    include:
    - trunk

variables:
  INFRASTRUCTURE: "AZUREPIPELINES"
  TRIAL_REPORTER: "verbose"
  CI: "true"

jobs:

- template: 'macos_test_jobs.yml'
  parameters:
    pythonVersions:
      py37: "3.7"
      py38: "3.8"
      py39: "3.9"

- template: 'windows_test_jobs.yml'
  parameters:
    pythonVersions:
      py37: "3.7"
      py38: "3.8"
      py39: "3.9"
    reactor: select

- template: 'windows_test_jobs.yml'
  parameters:
    pythonVersions:
      py37: "3.7"
      py38: "3.8"
      py39: "3.9"
    reactor: iocp
